---
name: Deploy to Vercel
on:
  push:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Deploy to Vercel
        run: |
          export VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}
          export VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}  # added by hand
          export VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}

          vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
          vercel build --prod --token="$VERCEL_TOKEN"
          vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
